import type {Metadata} from "next";

import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Omen Records",
  description: "Generated by nais",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="dark flex min-h-screen w-full justify-between flex-col">
        <Header />
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70 mt-20">
          © {new Date().getFullYear()} Nvis
        </footer>
      </body>
    </html>
  );
}
