import type {Metadata} from "next";

import {GeistSans} from "geist/font/sans";
import {GeistMono} from "geist/font/mono";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Omen Records",
  description: "Generated by nais",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html className={`${GeistSans.variable} ${GeistMono.variable}`} lang="en">
      <body className="dark flex min-h-screen w-full flex-col justify-between bg-background">
        <Header />
        <main>{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} All Rights Reserved.
        </footer>
      </body>
    </html>
  );
}
