import type {Metadata} from "next";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "OR",
  description: "Generated by nais",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="dark container flex min-h-screen w-full flex-col justify-between">
        <Header />
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} Nvis
        </footer>
      </body>
    </html>
  );
}
